name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey **#** , welcome to the repository, Thanks for Raising an Issue. Your contributions means a lot to us !!'
        pr-message: 'Hey **#** , welcome to the repository, Thanks for you active contributions !!'
